### ISSUE TITLE
Manage banner-entries bug

### ISSUE THREAD

**Issue by andersro93** [Magestore/Bannerslider-Magento2#54]
### Platform information:

Magento 2.1
### Trying to:

Navigate to banners to manage and add banners to a slider
### Expected:

Grid with all banners
### Got:

```
1 exception(s):
Exception #0 (ReflectionException): Class Magestore\BannerSlider\Ui\Component\Listing\Column\Image does not exist

Exception #0 (ReflectionException): Class Magestore\BannerSlider\Ui\Component\Listing\Column\Image does not exist
#0 /home/*******/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magestore\\Banne...')
#1 /home/*******/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magestore\\Banne...')
#2 /home/*******/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magestore\\Banne...')
#3 /home/*******/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magestore\\Banne...', Array)
#4 /home/*******/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(106): Magento\Framework\ObjectManager\ObjectManager->create('Magestore\\Banne...', Array)
#5 /home/*******/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(93): Magento\Framework\View\Element\UiComponentFactory->createChildComponent(Array, Object(Magento\Framework\View\Element\UiComponent\Context), 'image')
#6 /home/*******/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(169): Magento\Framework\View\Element\UiComponentFactory->createChildComponent(Array, Object(Magento\Framework\View\Element\UiComponent\Context), 'banner_grid_col...')
#7 /home/*******/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('banner_grid_lis...', NULL, Array)
#8 /home/*******/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'banner_grid_lis...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#9 /home/*******/public_html/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#10 /home/*******/public_html/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#11 /home/*******/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#12 /home/*******/public_html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#13 /home/*******/public_html/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#14 /home/*******/public_html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#15 /home/*******/public_html/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#16 /home/*******/public_html/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#17 /home/*******/public_html/var/generation/Magento/Framework/View/Page/Config/Interceptor.php(37): Magento\Framework\View\Page\Config->publicBuild()
#18 /home/*******/public_html/vendor/magento/framework/View/Result/Page.php(227): Magento\Framework\View\Page\Config\Interceptor->publicBuild()
#19 /home/*******/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#20 /home/*******/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#21 /home/*******/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#22 /home/*******/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#23 /home/*******/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#24 {main}
```

**Comment by pinicio** [comment]
Same here.

**Comment by scheung38** [comment]
It seems to work LOCALLY, after cloning Bannerslider, and moved to newly created folder

code/Magestore 
to my local MAMP development as

/Applications/MAMP/htdocs/Mage2.1.6/app/code/Magestore/Bannerslider

I see the problem when deployed to host provider, where upon clicking the Manage Sliders I get

1 exception(s):
Exception #0 (ReflectionException): Class Magestore\BannerSlider\Ui\Component\Listing\Column\Image does not exist

upon changing from Bannerslider to BannerSlider as suggested in #54

#54

Now I don't get the exceptions but the same redirect back to Dashboard instead of the expected page as you also experienced?

**Comment by prestashoppay** [comment]
Hi,

Installed Magestore bannerslider module in magento2.1.6 Admin panel "**manage banner**" section i getting below error ,


`i:0;s:77:"Class Magestore\BannerSlider\Ui\Component\Listing\Column\Image does not exist"`


Kindly let us know your suggestion to fix the issues.

**Comment by avadh88** [comment]
Hi,
"Class Magestore\BannerSlider\Ui\Component\Listing\Column\Image does not exist"
" Class Magestore\BannerSlider\Ui\Component\Listing\Column\Slider does not exist"

Solutions

Goto "app/code/Megastore/Bannerslider/view/adminhtml/ui_component/banner_grid_listing.xml"this Directory and replace below code.

'column name="image" class="Magestore\BannerSlider\Ui\Component\Listing\Column\Image"' replace 'column name="image" class="Magestore\Bannerslider\Ui\Component\Listing\Column\Image"'

'column name="slider_id" class="Magestore\BannerSlider\Ui\Component\Listing\Column\Slider"' to
'column name="slider_id" class="Magestore\Bannerslider\Ui\Component\Listing\Column\Slider"'

'actionsColumn name="actions" class="Magestore\BannerSlider\Ui\Component\Listing\Column\BannerstatusActions"' to
'actionsColumn name="actions" class="Magestore\Bannerslider\Ui\Component\Listing\Column\BannerstatusActions"'

**Comment by nabakishore009** [comment]
megastore showing not opening inside admin panel
